apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeployment
  namespace: test-ns
  labels:
    app: webdeploy
spec:
  strategy:
    type: Recreate
  replicas: 2
  selector:
    matchLabels:
      app: webapp1
  template:
     metadata:
       name:  combinedpod
       labels:
         app: webapp1
       namespace: test-ns
     spec:
       containers:
       - name: webcontainer
         image: vikasaroor/maven-web-application:TAG
         ports:
         - containerPort: 8081
       - name: nginx
         image: nginx
         ports:
         - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: deploysvc
  namespace: test-ns
  labels:
    ser: depnp
spec:
  selector:
    app: webapp1
  type: NodePort
  ports:
    - name: webport
      port: 8080
      targetPort: 8080
    - port: 80
      targetPort: 80
      name: ngxport
